services:
  - type: web
    name: college-award-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Optional, Render assigns one automatically if omitted
      - key: DB_HOST
        value: your-mysql-host-url
      - key: DB_USER
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: college_award_db

  - type: web
    name: college-award-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    plan: free
